runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|woff|otf|ttf|eot|svg))$
  static_files: dist/imobiliaria/\1
  upload: dist/imobiliaria/(.*)
- url: /(.*)
  static_files: dist/imobiliaria/index.html
  upload: dist/imobiliaria/index.html