runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|woff|otf|ttf|eot|svg))$
  static_files: imobiliaria/\1
  upload: imobiliaria/(.*)
- url: /(.*)
  static_files: imobiliaria/index.html
  upload: imobiliaria/index.html